### ISSUE TITLE
Aufgabe 1: LED an- und ausschalten

### ISSUE THREAD

**Issue by a-meg-s** [a-meg-s/episode-2-java#1]
**Aufgabe 1**
Teilaufgabe 1.1
Erstellen Sie die Methode ledsOnOff in der Klasse ClientApp, die anschliessend in der Methode main
aufgerufen wird. In der Methode ledsOnOff soll Folgendes gemacht werden:

1. Lesen Sie (von der Tastatur) die Anzahl LEDs ein (z.B. 16 LEDs), die dem Steckboard hinzugefügt werden sollen. Die Anzahl LEDs darf nicht grösser als die maximal erlaubte Anzahl LEDs sein, die der API-Dokumentation entnommen werden kann.
2. Fügen Sie die gewünschte Anzahl LEDs dem Steckboard hinzu. Mit welcher Methode der Klasse LedService kann das gemacht werden? Falls Sie dies nicht wissen, konsultieren Sie die APIDokumentation.
3. Halten Sie die Ausführung der Methode ledsOnOff für 2 Sekunden an, bevor es weiter geht. Mit welcher Methode der Klasse LedService kann diese bewerkstelligt werden? Falls Sie dies nicht wissen, sehen Sie sich die API-Dokumentation der Klasse LedSservice an.
4. Schalten Sie alle LEDs ein, wobei das Einschalten von rechts nach links erfolgen soll. Mit welcher Methode der Klasse LedService kann dies vorgenommen werden? Und welche Kontrollstruktur eignet sich für die Implementierung von wiederkehrenden Arbeiten?
5. Halten Sie die Ausführung der Methode ledsOnOff für 250 Millisekunden an, bevor es weiter geht.
6. Schalten Sie alle LEDs aus, wobei das Ausschalten in umgekehrter Reihenfolge (von links nach rechts) erfolgen soll. Welche Methode der Klasse LedService kann dazu verwendet werden?
7. Halten Sie die Ausführung der Methode ledsOnOff für 250 Millisekunden an, bevor es weiter geht.
8. Wiederholen Sie die Schritte 4, 5, 6, und 7 drei Mal, indem diese in einer passenden Schleife ausgeführt werden.
9. Halten Sie anschliessend die Ausführung der Methode ledsOnOff für 2 Sekunden an.
10. Setzen Sie die Anzeige zurück. Welche Methode der Klasse LedService eignet sich dafür? Und, gibt es evtl. mehrere Möglichkeiten?

Sie werden sicher festgestellt haben, dass alle LEDs offenbar gleichzeitig eingeschaltet bzw. ausgeschaltet
werden. Passen Sie den Code so an, dass das Einschalten bzw. Ausschalten von einzelnen LEDs mit einer
kurzer Verzögerung erfolgt, um den ganzen Vorgang etwas sichtbarer zu machen. Experimentieren Sie
etwas mit der Dauer der Verzögerung, bis Sie mit dem Ablauf zufrieden sind. Welche Methode dazu
eingesetzt werden kann, entnehmen Sie bitte der API-Dokumentatio

**Comment by Zinga14** [comment]
`package ch.hslu.prg.leds;

import ch.hslu.prg.leds.proxy.LedService;
import java.util.Scanner;

public class ClientApp {

	private static void LedsOnOff(LedService led) {
		Scanner sc = new Scanner(System.in);
		int userLeds;
		boolean eingabe = false;
		do {
			System.out.print("Bitte geben Sie eine Zahl ein: ");
			userLeds = sc.nextInt();
			
			//Schleife mit abfrage für Leds
			if (userLeds > LedService.MAX_NUMBER_OF_LEDS) {
				System.out.print("Die Zahl ist zu gross. Bitte geben Sie eine kleinere Zahl ein!");
				eingabe = false;
			} else if (userLeds <= 0) {
				System.out.print("Die Zahl ist zu klein. Bitte geben Sie eine grössere Zahl ein!");
				eingabe = false;
			} else if (userLeds <= LedService.MAX_NUMBER_OF_LEDS && userLeds >= 0) {
				eingabe = true;
			} else {
				System.out.print("Es gab einen Fehler, bitte versuchen Sie es erneut.");
				eingabe = false;
			}

		} while (eingabe = false);
		//Leds hinzufügen
		led.addLeds(userLeds);
		
		//Methode für 2sek anhalten
		led.stopExecutionFor(2000);
		// led.turnLedOn(1);
		
		// Ganze funktion 3x ausführen
		for (int x = 0; x <= 3; x++) {
			
			//Leds anschalten
			for (int i = 0; i <= userLeds; i++) {
				led.turnLedOn(i);
			}
			//Methode für 250Milisek anhalten
			led.stopExecutionFor(250);
			for (int i = userLeds; i >= 0; i--) {
				led.turnLedOff(i);
			}
		}
		
		//Methode für 2sek anhalten
		led.stopExecutionFor(2000);
		
		//Led's zurücksetzen
		led.reset();
	}

	public static void main(String[] args) {

		LedService led = new LedService();
		/*
		 * led.addLeds(5); 
		 * led.turnLedOn(2);
		 * 
		 */
		LedsOnOff(led);

	}

}
`

**Comment by Zinga14** [comment]
Neuer Code mit Optionaler Aufgabe 1.2 ergänzt
Neu kann die Farbe der LED's gesetzt werden

`package ch.hslu.prg.leds;

import ch.hslu.prg.leds.proxy.LedService;
import ch.hslu.prg.leds.proxy.LedColor;

import java.util.Scanner;

public class ClientApp {

	private static void LedsOnOff(LedService led) {
		Scanner sc = new Scanner(System.in);
		
		//Fabre der LED's setzen
		LedColor ledColor = LedColor.RANDOM;
		int userLeds;
		boolean eingabe = false;
		do {
			System.out.print("Bitte geben Sie eine Zahl ein: ");
			userLeds = sc.nextInt();

			// Schleife mit abfrage für Leds
			if (userLeds > LedService.MAX_NUMBER_OF_LEDS) {
				System.out.print("Die Zahl ist zu gross. Bitte geben Sie eine kleinere Zahl ein!");
				eingabe = false;
			} else if (userLeds <= 0) {
				System.out.print("Die Zahl ist zu klein. Bitte geben Sie eine grössere Zahl ein!");
				eingabe = false;
			} else if (userLeds <= LedService.MAX_NUMBER_OF_LEDS && userLeds >= 0) {
				eingabe = true;
			} else {
				System.out.print("Es gab einen Fehler, bitte versuchen Sie es erneut.");
				eingabe = false;
			}

		} while (eingabe = false);
		// Leds hinzufügen
		led.addLeds(userLeds, ledColor);

		// Methode für 2sek anhalten
		led.stopExecutionFor(2000);
		// led.turnLedOn(1);

		// Ganze funktion 3x ausführen
		for (int x = 0; x <= 3; x++) {

			// Leds anschalten
			for (int i = 0; i <= userLeds; i++) {
				led.turnLedOn(i);
				// Verzögerung zwischen Led's
				led.setDelayInMillis(50);

			}
			// Methode für 250Milisek anhalten
			led.stopExecutionFor(250);
			for (int i = userLeds; i >= 0; i--) {
				led.turnLedOff(i);
				// Verzögerung zwischen Led's
				led.setDelayInMillis(50);
			}
		}

		// Methode für 2sek anhalten
		led.stopExecutionFor(2000);

		// Led's zurücksetzen
		led.reset();
	}

	public static void main(String[] args) {

		// Instanzerstellung von LedService
		LedService led = new LedService();
		/*
		 * Bsp. manuelle erstellung / Aufruf... led.addLeds(5); led.turnLedOn(2);
		 * 
		 */

		// Methodenaufruf LedsOnOff
		LedsOnOff(led);

	}
}
`
