### ISSUE TITLE
Aufgabe 6: Ein Quadrat auf den LEDs zeichnen

### ISSUE THREAD

**Issue by a-meg-s** [a-meg-s/episode-2-java#3]
**Aufgabe 6**
_Teilaufgabe 6.1_
In dieser Aufgabe geht es darum, dass basierend auf den Eingaben für den äusseren Punkt topLeft und die
Länge der Seite ein Quadrat gezeichnet wird. Erstellen Sie dazu die Methode showSquare in der Klasse
ClientApp, die danach in der Methode main aufgerufen wird. In der Methode showSquare soll Folgendes
gemacht werden:

1. Fügen Sie die maximal mögliche Anzahl LEDs dem Steckboard hinzu (nutzen Sie dabei die Konstante, die von der Klasse LedSerivce zur Verfügung gestellt wird).
2. Lesen Sie die Nummer des LEDs von der Tastatur ein, das als “topLeft“ Punkt figurieren soll. Damit ist die Nummer des LEDs gemeint, das die linke obere Ecke darstellt.
3. Lesen Sie die Länge der Seite des Quadrats von der Tastatur ein.
4. Zeichnen Sie basierend auf den getätigten Eingaben ein Quadrat. Dabei sollen nur die LEDs, die dem Rahmen des Quadrats “gehören“, eingeschaltet werden.
5. Halten Sie die Ausführung der Methode showSquare für 5 Sekunden an, bevor es weiter geht.
6. Setzen Sie am Schluss die Anzeige zurück. Kontrollieren Sie anschliessend, ob die Zeichnung des Quadrats für unterschiedliche Eingaben für “topLeft“ und Seitenlänge korrekt funktioniert.

_Hinweise:_

- Überprüfgen Sie die Korrektheit der Eingaben, bevor das “Zeichnen des Qudrats“ gestartet wird. Wenn z.B. als “topLeft“ das LED mit der Nummer 34 angegeben wird, für die Länge der Seite aber 10 eingegeben wird, kann ein solches Quadrat nicht gezeichnet werden, weil es ausserhalb des Steckboards liegen würde. Sollte aber für die Länge der Seite der Wert 3 eingegeben werden, würde das funktionieren.
- Fragen Sie die Eingabe so lange ab, bis eine korrekte bzw. passende Eingabe getätigt wird.

_Teilaufgabe 6.2 (Fakultativ)_
Ergänzen Sie die Implementierung der Methode showSquare so, dass auch die beiden Diagonalen des
Quadrats gezeichnet werden. Wenn man den Umgang mit Methoden üben möchte, könnte das Zeichnen
der beiden Diagonalen in einer separaten Methode realisiert werden, die aus der Methode showSquare
aufgerufen wird.

**Comment by a-meg-s** [comment]
Fast fertig, es macht ein Quadrat, und gibt eine Fehlermeldung, wenn es über die Grenzen geht, aber es versucht, es zu zeichnen, bevor die Fehlermeldung. ich bin immer noch auf die Korrektur dieses spezifischen Aspekts arbeiten.

`
	public static void ShowSquare(LedService led) {

		// Add the maximum possible number of LEDs to the breadboard.
		led.addLeds(LedService.MAX_NUMBER_OF_LEDS);

		// Read the number of the LED that should be the top-left point of the square.
		Scanner scanner = new Scanner(System.in);
		System.out.print("Bitte geben Sie die Nummer des LEDs für den oberen linken Punkt ein: ");
		int topLeft = scanner.nextInt();

		// Read the length of the side of the square.
		System.out.print("Bitte geben Sie die Länge der Seiten des Quadrats ein: ");
		int sideLength = scanner.nextInt();

		// Check if the input is valid.
		int rows = LedService.MAX_ROWS;
		int columns = LedService.MAX_COLUMNS;

		// Schleiffe für den Rahmen
		for (int i = 0; i < rows; i++) {
			for (int j = 0; j < columns; j++) {

				if (topLeft < 0 || topLeft >= LedService.MAX_NUMBER_OF_LEDS) {
					System.out.println("Die Nummer des LEDs für den oberen linken Punkt ist ungültig.");
					return;
				}
				if (sideLength <= 0) {
					System.out.println("Die Länge der Seiten des Quadrats ist ungültig.");
					return;
				}
			}
		}

		// Calculate the X-coordinate of the top left corner.
		int xCoordinate = topLeft / 16;

		// Calculate the Y-coordinate of the top left corner.
		int yCoordinate = topLeft % 16;

		// Draw the square.
		// for (int i = xCoordinate; i < xCoordinate + sideLength; i++) {
		//// led.turnLedOn(i * 16 + j);

		// Draw the square.
		for (int i = xCoordinate; i >= xCoordinate - sideLength; i--) {
			for (int j = yCoordinate; j >= yCoordinate - sideLength; j--) {
				led.turnLedOn(i * 16 + j);
			}
		}

		if (xCoordinate - sideLength < LedService.MAX_COLUMNS || yCoordinate + sideLength > LedService.MAX_ROWS) {
			System.out.println("Das Quadrat überschreitet die Grenzen des LED-Arrays.");
			ShowSquare(led);
			return;
		}

		// Pause for 5 seconds.
		led.stopExecutionFor(5000);

		// Reset the display.
		// led.reset();
	}`

**Comment by Zinga14** [comment]
Ich glaube die Überprüfung sollte vielleicht nicht in einer Schleife sein. Vielleicht könnte es daran liegen..?
